[info]
parent="background"

[[spawns]]
x = 10.0
y = 15.0
[[spawns]]
x = 5.0
y = 25.0
[[spawns]]
x = 50.0
y = 32.0
[[spawns]]
x = 6.0
y = 89.0

[scale]
coefficiantx = 1.0
coefficianty = 1.0

[physics]
g = 10.0