[info]
parent="pumpkin"

[animation]
frameDelay = 5.0
framenum = 5.0
frameX = 0.0
frameY = 0.0
frameWidth = 16.0
frameHeight = 50.0

[buffs.speed]
    x = 5.0
    y = 5.0

[scale]
coefficiantx = 3.0
coefficianty = 3.0

