[margins]
leftmargin = 105.0
topmargin = 125.0

[size]
width = 70.0
height = 40.0

[scale]
coefficiantx = 4.0
coefficianty = 4.0

[button]
text = "Confirm\ngame"
textposition = "center"

[fonts]
font = 9.0
fontcolor = "white"