[info]
parent="button"

[margins]
leftmargin = 105.0
topmargin = 92.5

[scale]
coefficiantx = 4.0
coefficianty = 4.0

[button]
text = "Join game"
textposition = "center"

[fonts]
font = 9.0
fotntcolor = "white"
