[margins]
leftmargin = 190.0
topmargin = 170.0

[size]
width = 70.0
height = 40.0

[scale]
coefficiantx = 2.5
coefficianty = 2.5

[button]
text = "Save config"
textposition = "center"
font = 9.0
fontcolor = "white"
