[info]
parent="button"

[margins]
leftmargin = 190.0
topmargin = 170.0

[scale]
coefficiantx = 2.5
coefficianty = 2.5

[button]
text = "Save config"
textposition = "center"

[fonts]
font = 9.0
fontcolor = "white"
