[info]
parent="button"

[margins]
leftmargin = 105.0
topmargin = 125.0

[scale]
coefficiantx = 4.0
coefficianty = 4.0

[text]
symbols = "Confirm\ngame"
position = "center"

[fonts]
font = 9.0
fontcolor = "white"