[margins]
leftmargin = 110.0
topmargin = 37.0

[size]
width = 70.0
height = 40.0

[scale]
coefficiantx = 3.0
coefficianty = 2.5

# [button]
# text = "Start game"
# textposition = "center"
# font = 9.0
# fontcolor = "white"
