[info]
parent="background"
gamerole = "gamemap"

[[spawns]]
x = 10
y = 15
[[spawns]]
x = 5
y = 25
[[spawns]]
x = 50
y = 32
[[spawns]]
x = 6
y = 89

[scale]
x = 1.0
y = 1.0



[physics]
g = 10.0

# [camera]
# maxzoom = 55.0
# minzoom = 40.0
# zoom = 50.0