[info]
parent="pumpkin"

[animation]
frameDelay = 5.0
frameNum = 5
frameX = 0.0
frameY = 0.0
frameWidth = 16.0
frameHeight = 50.0

[buffs.speed]
    x = 2.0
    y = 2.0

[scale]
coefficiantx = 3.0
coefficianty = 3.0

