[info]
parent="pumpkin"

[animation]
frameDelay = 5.0
frameNum = 5
frameX = 0.0
frameY = 0.0
frameWidth = 16.0
frameHeight = 50.0

[buffs.speed]
    x = 2.0
    y = 2.0

[scale]
x = 3.0
y = 3.0

[effects]
tracecolorbegin = [255.0, 168.0, 5.0, 255.0]
tracecolorend = [242.0, 200.0, 12.0, 255.0]

